### ISSUE TITLE
Úkol 001 - inicializační úkoly a první program

### ISSUE THREAD

**Issue by RealRodein** [RealRodein/github-vk-is-2024-sk1#1]
## To-Do

- [x] na GitHubu vytvořit první issue s názvem `Úkol 001 - inicializační úkoly a první program`
- [x] provést spojení mezi local repo a githup repo
- dát clone na repo z githubu
- nastavení identifikace pro commit
- [x] na local repo změnit obsah sourboru `README.md` a provést první init commit
- [x] uvnitř repo vytvořit složku s názvem `IS-Projekty`
- zde vytvořit další `README.md`
- commit a push
- zde vytvořit program s názvem `001-app1-vypis-rady`
